name: Snap2Text after every push

on:
  push:
    branches-ignore:
      - snap2txt
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snapshot:
    uses: overandor/hf-spaces-snap2txt/.github/workflows/repository-snap2txt.yml@1d9b7a71b7245f98c85cd9c8619ddf124d0d8db2
